### ISSUE TITLE
I'd like to take over development for this project!

### ISSUE THREAD

**Issue by JAM0005** [JMSS-time/time-updated#2]
I hope I'm not too late to apply for this. I have some experience in both javascript and html, and I've had a look at your source code and I understand it in broad terms. I'm reasonably confident I can run and update this site.

**Comment by ehne** [comment]
Hi! 

Thanks for reaching out about taking over the reins on the JMSS-Time project. You're not too late to apply! This website is run by students, for students. And we want to pass the project on to the next generation (we graduated from JMSS in 2021).

The main component of JMSS-Time is the clock/timetable website ( https://jmss-time.github.io/time-updated ), and we want to keep that part **fast**, **up-to-date**, and **easy to use**. Most of your time will just be making sure that the timetable is accurate, meaning that you'll need to update the timetable code. However, there is room to add new features and external sites to supplement the JMSS-Time experience.

Before we add you to the JMSS-Time org, there are a couple of things I want to ask you:

- **How much experience do you have making websites?** Specifically, front end only websites (JMSS-Time is fully hosted on GitHub Pages, which does not allow for a server component).
- **Do you have an example project that you have worked on that closely resembles the technology stack used by JMSS-Time?** (Statically hosted, Vanilla JS, CSS and HTML)
- If so, could you please link it.
- **Do you have any ideas for new features or sites that could supplement JMSS-Time?** If so, please give a rough outline.

(These questions are more just so that I know that the website will be kept in good hands. In reality you will probably only be updating the [one or two lines](https://github.com/JMSS-time/time-updated/blob/29d4a109d888667497406e13a80e32d57ab09eda/script.js#L85-L100) that contain the timetable)

Thanks for reaching out, and I look forward to hearing back from you.

:)

**Comment by JAM0005** [comment]
Hi,

Sorry for the late reply.
Unfortunately I don't have much experience making websites, as most of my
coding experience came from creating graphics and game mechanics for
several projects of the years. I have written a few test websites in
html/javascript, but I'm a little rusty, to be honest.
I had an idea for a new feature for the website, though. In a similar
fashion to how the main clock is displayed, underneath it the times until
special events (e.g. the swimming carnival today) happen. It would require
most of the same code as the clock as it's effectively doing the same
thing; the only changes would be to the way events are stored. Of course,
this would have to be updated fairly regularly.

Thanks for your time,
David

**Comment by ehne** [comment]
Hi David!

Thanks for answering those questions! I believe that you and Shaunak would be great to run the JMSS-Time website.

While you say that you don't have much experience making websites, I reckon JMSS-Time is easy enough to understand. As I said, most of the time is spent updating the timetable data, which shouldn't be too hard. And of course, you can make your own timers and countdowns as you've suggested, and that might be a way to brush up on your js skills!

I'll invite you to the JMSS-Time organisation, and you should receive an email from GitHub shortly.

Now, in terms of running the website, I wrote a massive document, but I'll spare you that mess. Here's the TL;DR:

- Keep the website (and any subsequent websites/features) fast, easy to use, and accurate.
- Use Vanilla JS and don’t rely on external libraries/frameworks. Try to keep it to one script request. (No analytics scripts)
- Check your algorithm’s efficiency and try to make the best possible one. No student likes dealing with a slow website.
- Use the Semistandard JS code style and linter to keep your code standardised and to spot bugs.
- Make sure that the website is as accurate as it can be. Students rely on JMSS-Time to tell them the truth.
- Make sure that the website is accessible and easy to use.
- Try to keep within the already laid out design conventions of JMSS-Time. Fairly monochrome on a vibrant blurred background. There is wiggle room here, just make it look nice, really.
- The colours used are from the [Tailwindcss colour palette](https://v2.tailwindcss.com/docs/customizing-colors) (except for white, which is #fff). The font used is IBM Plex Mono.
- Commits should be in the format of a [gitmoji](https://gitmoji.dev/) followed by what the commit does.

If you know what this stuff means, that's great. If not, don't fret it, it doesn't really matter lol. Just make it nice and keep the timetable up to date!

Thanks, and it's great to have you onboard :)
